DROP TABLE MYCODE.EMPLOYEE;

CREATE TABLE MYCODE.EMPLOYEE (
	EMPLOYEE_ID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	EMAIL_ID VARCHAR(150) NOT NULL,
	HIRE_DATE DATE,
	HIRING_MANAGER_ID INT,
	PRIMARY KEY(EMPLOYEE_ID)
) ;
