//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.12 at 08:34:28 PM IST 
//


package com.rightkarma.learnjava.jaxb.xsdtojava;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for someclass complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="someclass">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="someint" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="somestring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="somedate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "someclass", propOrder = {
    "someint",
    "somestring",
    "somedate"
})
public class Someclass {

    protected int someint;
    protected String somestring;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar somedate;

    /**
     * Gets the value of the someint property.
     * 
     */
    public int getSomeint() {
        return someint;
    }

    /**
     * Sets the value of the someint property.
     * 
     */
    public void setSomeint(int value) {
        this.someint = value;
    }

    /**
     * Gets the value of the somestring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSomestring() {
        return somestring;
    }

    /**
     * Sets the value of the somestring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSomestring(String value) {
        this.somestring = value;
    }

    /**
     * Gets the value of the somedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSomedate() {
        return somedate;
    }

    /**
     * Sets the value of the somedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSomedate(XMLGregorianCalendar value) {
        this.somedate = value;
    }

}
