DROP TABLE MYCODE.EMPLOYEE_HISTORY;

CREATE TABLE MYCODE.EMPLOYEE_HISTORY (
	HISTORY_ID INT NOT NULL,
	EMPLOYEE_ID INT NOT NULL,
	ENTRY_DATE TIMESTAMP,
	ENTRY VARCHAR(200),
	PRIMARY KEY(HISTORY_ID)
) ;